print("COMENTARIOS")
#este es un comentario diferente

"Este es un comentario"

""" Este es un comentario
multilinea"""
print("-------------")
print("Tipos de datos")

numero= 15
print(numero, type(numero))
#Tipo de dato flotante

numero_flotante=15.5
print(numero_flotante, type(numero_flotante))

#Tipo de dato numero complejo
numero_complejo= 5 + 6j
print(numero_complejo, type(numero_complejo))
 #Tipo de dato String
nombre= "ernesto"
print(nombre, type(nombre))

#Tipo de dato booleano
verdadero_falso= 3 == 3
print(verdadero_falso, type(verdadero_falso))

